apiVersion: batch/v1
kind: Job
metadata:
  name: job1
spec:
  template:
    metadata:
      labels:
        job: example-job
    spec:
      restartPolicy: Never
      containers:
        - name: busybox-job
          image: busybox:latest
          command: ["/bin/sh", "-c", "echo 'Hello from Kubernetes Job!'; sleep 10; echo 'Job Completed!'"]
