apiVersion: v1
kind: Namespace
metadata:
  name: namespace-one
---
apiVersion: v1
kind: Namespace
metadata:
  name: namespace-two
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-in-namespace-one
  namespace: namespace-one
  labels:
    app: multi-container-one
spec:
  volumes:
    - name: shared-data
      emptyDir: {}
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html
      ports:
        - containerPort: 80
    - name: busybox-container
      image: busybox:latest
      command: ["/bin/sh", "-c", "while true; do echo 'Hello from Namespace One' > /output/index.html; sleep 5; done"]
      volumeMounts:
        - name: shared-data
          mountPath: /output
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-in-namespace-two
  namespace: namespace-two
  labels:
    app: multi-container-two
spec:
  volumes:
    - name: host-storage
      hostPath:
        path: /mnt/data
        type: DirectoryOrCreate
  containers:
    - name: alpine-container
      image: alpine:latest
      command: ["/bin/sh", "-c", "while true; do echo 'Hello from Namespace Two' > /mnt/host/namespace-two.txt; sleep 5; done"]
      volumeMounts:
        - name: host-storage
          mountPath: /mnt/host
    - name: ubuntu-container
      image: ubuntu:latest
      command: ["/bin/bash", "-c", "while true; do cat /mnt/host/namespace-two.txt || echo 'Waiting for data...'; sleep 5; done"]
      volumeMounts:
        - name: host-storage
          mountPath: /mnt/host
