apiVersion: v1
kind: Pod
metadata:
  name: nginx-sidecar-pod
  labels:
    app: nginx-sidecar
spec:
  volumes:
    - name: log-volume
      emptyDir: {}
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - name: log-volume
          mountPath: /var/log/nginx
      ports:
        - containerPort: 80
    - name: log-sidecar
      image: busybox:latest
      command: ["/bin/sh", "-c", "while true; do cat /var/log/nginx/access.log >> /output/logs.txt; sleep 5; done"]
      volumeMounts:
        - name: log-volume
          mountPath: /var/log/nginx
